name: flutter_carplaybr
description: Flutter Apps are now on Apple CarPlay. This package aims to make it safe to use iPhone apps made with Flutter in the car by integrating with CarPlay.
version: 1.1.12
homepage: https://github.com/Fix-Pay/flutter_carplaybr#readme
repository: https://github.com/Fix-Pay/flutter_carplaybr
issue_tracker: https://github.com/Fix-Pay/flutter_carplaybr/issues

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.18.0-18.0.pre.54"

dependencies:
  flutter:
    sdk: flutter
  uuid: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterCarplayPlugin
